from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


SCRIPT_PATH = (
    Path(__file__).resolve().parent.parent / "scripts" / "normalize_generated_sdk.py"
)


VALIDATION_ERROR_WITH_CONTEXT = """/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Context = {};

export type Loc = string | number;

export type ValidationError = {
  ctx?: Context | undefined;
  input?: any | undefined;
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/** @internal */
export const Context$inboundSchema: z.ZodMiniType<Context, unknown> = z.object(
  {},
);

export function contextFromJSON(
  jsonString: string,
): SafeParseResult<Context, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Context$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Context' from JSON`,
  );
}

/** @internal */
export const Loc$inboundSchema: z.ZodMiniType<Loc, unknown> = smartUnion([
  types.string(),
  types.number(),
]);

export function locFromJSON(
  jsonString: string,
): SafeParseResult<Loc, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Loc$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Loc' from JSON`,
  );
}

/** @internal */
export const ValidationError$inboundSchema: z.ZodMiniType<
  ValidationError,
  unknown
> = z.object({
  ctx: types.optional(z.lazy(() => Context$inboundSchema)),
  input: types.optional(z.any()),
  loc: z.array(smartUnion([types.string(), types.number()])),
  msg: types.string(),
  type: types.string(),
});

export function validationErrorFromJSON(
  jsonString: string,
): SafeParseResult<ValidationError, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ValidationError$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidationError' from JSON`,
  );
}
"""


CONFIG_WITH_VERSIONED_METADATA = """/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export const SDK_METADATA = {
  language: "typescript",
  openapiDocVersion: "7.0.0",
  sdkVersion: "0.1.0",
  genVersion: "2.827.0",
  userAgent: "speakeasy-sdk/typescript 0.1.0 2.827.0 7.0.0 agent-control",
} as const;
"""


TEMPLATE_CONTROL_INPUT_WITHOUT_UNSTABLE_TYPE_COMMENT = """/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

export type TemplateControlInput = {};
"""


TEMPLATE_CONTROL_INPUT_WITH_UNSTABLE_TYPE_COMMENT = """/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Template-backed input payload for control create/update requests.
 */
export type TemplateControlInput = {};
"""


def _write_schema(tmp_path: Path, *, include_context_fields: bool) -> Path:
    properties: dict[str, object] = {
        "loc": {"type": "array"},
        "msg": {"type": "string"},
        "type": {"type": "string"},
    }
    if include_context_fields:
        properties["ctx"] = {"type": "object"}
        properties["input"] = {}

    schema_path = tmp_path / "openapi.json"
    schema_path.write_text(
        json.dumps(
            {
                "components": {
                    "schemas": {
                        "ValidationError": {
                            "type": "object",
                            "properties": properties,
                        }
                    }
                }
            }
        ),
        encoding="utf-8",
    )
    return schema_path


def _write_generated_file(tmp_path: Path) -> Path:
    generated_dir = tmp_path / "generated"
    models_dir = generated_dir / "models"
    lib_dir = generated_dir / "lib"
    models_dir.mkdir(parents=True)
    lib_dir.mkdir(parents=True)
    file_path = models_dir / "validation-error.ts"
    file_path.write_text(VALIDATION_ERROR_WITH_CONTEXT, encoding="utf-8")
    (models_dir / "template-control-input.ts").write_text(
        TEMPLATE_CONTROL_INPUT_WITHOUT_UNSTABLE_TYPE_COMMENT,
        encoding="utf-8",
    )
    (lib_dir / "config.ts").write_text(CONFIG_WITH_VERSIONED_METADATA, encoding="utf-8")
    return generated_dir


def test_normalizer_removes_context_fields_when_schema_omits_them(tmp_path: Path) -> None:
    schema_path = _write_schema(tmp_path, include_context_fields=False)
    generated_dir = _write_generated_file(tmp_path)

    subprocess.run(
        [
            sys.executable,
            str(SCRIPT_PATH),
            "--schema",
            str(schema_path),
            "--generated-dir",
            str(generated_dir),
        ],
        check=True,
    )

    normalized = (generated_dir / "models" / "validation-error.ts").read_text(encoding="utf-8")
    assert "Context$inboundSchema" not in normalized
    assert "contextFromJSON" not in normalized
    assert "ctx?: Context | undefined;" not in normalized
    assert "input?: any | undefined;" not in normalized


def test_normalizer_removes_context_fields_when_schema_includes_them(tmp_path: Path) -> None:
    schema_path = _write_schema(tmp_path, include_context_fields=True)
    generated_dir = _write_generated_file(tmp_path)

    subprocess.run(
        [
            sys.executable,
            str(SCRIPT_PATH),
            "--schema",
            str(schema_path),
            "--generated-dir",
            str(generated_dir),
        ],
        check=True,
    )

    normalized = (generated_dir / "models" / "validation-error.ts").read_text(encoding="utf-8")
    assert "Context$inboundSchema" not in normalized
    assert "contextFromJSON" not in normalized
    assert "ctx?: Context | undefined;" not in normalized
    assert "input?: any | undefined;" not in normalized


def test_normalizer_rewrites_sdk_metadata_to_stable_version(tmp_path: Path) -> None:
    schema_path = _write_schema(tmp_path, include_context_fields=True)
    generated_dir = _write_generated_file(tmp_path)

    subprocess.run(
        [
            sys.executable,
            str(SCRIPT_PATH),
            "--schema",
            str(schema_path),
            "--generated-dir",
            str(generated_dir),
        ],
        check=True,
    )

    normalized = (generated_dir / "lib" / "config.ts").read_text(encoding="utf-8")
    assert 'openapiDocVersion: "0.0.0"' in normalized
    assert (
        'userAgent: "speakeasy-sdk/typescript 0.1.0 2.827.0 0.0.0 agent-control"'
        in normalized
    )


def test_normalizer_removes_unstable_template_control_input_type_comment(
    tmp_path: Path,
) -> None:
    schema_path = _write_schema(tmp_path, include_context_fields=True)
    generated_dir = _write_generated_file(tmp_path)
    template_control_input = generated_dir / "models" / "template-control-input.ts"
    template_control_input.write_text(
        TEMPLATE_CONTROL_INPUT_WITH_UNSTABLE_TYPE_COMMENT,
        encoding="utf-8",
    )

    subprocess.run(
        [
            sys.executable,
            str(SCRIPT_PATH),
            "--schema",
            str(schema_path),
            "--generated-dir",
            str(generated_dir),
        ],
        check=True,
    )

    normalized = template_control_input.read_text(encoding="utf-8")
    assert normalized == TEMPLATE_CONTROL_INPUT_WITHOUT_UNSTABLE_TYPE_COMMENT
